# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev-master" ]
  pull_request:
    branches: [ "dev-master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: dev-master
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Setup Cosmos
      run: |
        sudo apt-get install yasm mkisofs make binutils git && \
          cd ~ && \
          mkdir cosmos && \
          cd cosmos && \
          git clone https://github.com/CosmosOS/Cosmos --depth 1 && \
          git clone https://github.com/CosmosOS/IL2CPU --depth 1 && \
          git clone https://github.com/CosmosOS/XSharp --depth 1 && \
          git clone https://github.com/CosmosOS/Common --depth 1 && \
          cd Cosmos && \
          make all && \
          sudo make install && \
          make nuget-install
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: sudo dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal